### ISSUE TITLE
Thanks for your project, little questions here

### ISSUE THREAD

**Issue by xhkyyy** [hasheddan/k8scr#2]
Hi, i am a beginner in kubernetes.
Thanks for your project, I learned that K8S-API-Server has a [Proxy](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#create-connect-proxy-pod-v1-core) feature.
I read the source code of this project and drew the diagram of its implementation. 
Do I understand it correctly?

<img width="1151" alt="1111111" src="https://user-images.githubusercontent.com/2297302/126871595-9d98accf-2218-4ac5-954a-693c1b52b699.png">

**Comment by hasheddan** [comment]
Hey @xhkyyy! Apologies for the delays response here! You have a pretty good idea here, though I'm not sure about the interaction between `k8scr` and "Registry". If you are just saying that the `k8scr` `Pod` is serving as "Registry" then you are spot on :)
