### ISSUE TITLE
What does -load mean in the image directive in the makefile?

### ISSUE THREAD

**Issue by marionxue** [hasheddan/k8scr#3]
```makefile
image:
	@docker build . -f distribution.Dockerfile -t hasheddan/k8scr-distribution:latest --load
```
What does `-load` mean in the image directive in the makefile? 🔼

**Comment by hasheddan** [comment]
@marionxue when using [buildx](https://docs.docker.com/engine/reference/commandline/buildx_build/) you must specify that you want to `--load` the image (i.e. `--output=type=docker`). If not using `buildx` it can be ignored :)

**Comment by marionxue** [comment]
@hasheddan Thank you for your reply. I think I have touched the unknown skill. 🆒
